### ISSUE TITLE
Shortcut Ctrl-ALT-s

### ISSUE THREAD

**Issue by bigretromike** [wallabag/firefox-ext-v2#30] opened 2016-09-07 09:35 UTC
Few of language use alt+s
but this should not conflict with ctrl + alt + s but it does.
Even if I hit ALT + S i get "adding" command 
It will be fine when changing to not used letter but the problem is that Alt + S shouldn't trigger Ctrl + Alt + S 

current tested on Windows 10
addon 0.0.10

**Comment by Simounet** [comment] 2016-09-26 20:43
Hmm, that's weird because I can't reproduce it. Tried on Windows 10 (and Ubuntu btw).

**Comment by bigretromike** [comment] 2016-09-27 05:59
Maybe thats something related with os lang, and keyboard layout as the one i tested was 'PL-pl'

On September 26, 2016 10:43:26 PM GMT+02:00, Simon Alberny <notifications@github.com> wrote:
>Hmm, that's weird because I can't reproduce it. Tried on Windows 10
>(and Ubuntu btw).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wallabag/firefox-ext-v2/issues/30#issuecomment-249691586

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment] 2016-10-05 10:07
I tested it few times, OS without Polish PL-pl keyboard setting wont throw this error

**Comment by Simounet** [comment] 2016-10-05 10:16
Ok, so it's a keyboard layout issue?

**Comment by bigretromike** [comment] 2016-10-05 10:43
The issue is this:
on PL-pl keyboard layout there is a character for ALT+S, but the plugin capture CTRL+ALT+S as ALT+S, preventing from using it. Workaround would be change S to anything not used by the layout.
But proper fix should capture CTRL+ALT+S not as ALT+S

**Comment by Simounet** [comment] 2016-10-05 12:01
Are you using the left ALT or the right ALT?

**Comment by bigretromike** [comment] 2016-10-05 12:05
left

**Comment by Simounet** [comment] 2016-10-05 12:10
Hmmm, I cannot reproduce it with a PL keyboard layout on Linux. It seems to be a Windows layout issue, more than an extension one.

**Comment by gruentee** [comment] 2016-12-28 20:38
Using FF 50.1.0 on Linux with German keyboard layout. 
I can't find a suitable key, no key seems to trigger the addon.

**Comment by Simounet** [comment] 2017-03-16 11:47
Closed because we won't fix it. This extension is deprecated in favour of [wallabagger](https://github.com/wallabag/wallabagger).

**Closed by Simounet** 2017-03-16 11:47 UTC
